FROM alpine:3.24

RUN apk add --no-cache \
    bash \
    build-base \
    linux-headers \
    clang \
    lld \
    llvm \
    musl-dev \
    binutils \
    cmake \
    ninja \
    git \
    gtest-dev \
    pkgconf \
    python3 \
    # Vulkan SDK
    vulkan-headers \
    vulkan-loader-dev \
    vulkan-validation-layers \
    spirv-tools \
    glslang \
    # Software rasterizer
    mesa-vulkan-swrast

RUN addgroup nyx && adduser -D -G nyx -s /bin/bash nyx
RUN mkdir /nyx && chown -R nyx:nyx /nyx && chmod 770 /nyx 

COPY --chown=nyx:nyx ./entrypoint.sh /nyx/entrypoint.sh
RUN chmod +x /nyx/entrypoint.sh

WORKDIR /nyx
USER nyx

ENTRYPOINT [ "/nyx/entrypoint.sh" ]
CMD [ "/bin/bash" ]